
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 36;
  public static final int SO = 10;
  public static final int MAJ = 4;
  public static final int REPEAT = 34;
  public static final int SC = 11;
  public static final int FOR = 25;
  public static final int MINUS = 19;
  public static final int STAR = 20;
  public static final int NOT = 9;
  public static final int AND = 7;
  public static final int CM = 23;
  public static final int UMIN = 3;
  public static final int NIL = 32;
  public static final int OR = 8;
  public static final int DIV = 21;
  public static final int UNTIL = 35;
  public static final int RO = 14;
  public static final int MIN_EQ = 5;
  public static final int PLUS = 18;
  public static final int MIN = 2;
  public static final int IF = 26;
  public static final int ID = 39;
  public static final int EOF = 0;
  public static final int RETURN = 37;
  public static final int error = 1;
  public static final int RC = 15;
  public static final int HAT = 22;
  public static final int NUMBER = 40;
  public static final int BO = 16;
  public static final int EQ = 12;
  public static final int ELSE = 27;
  public static final int BC = 17;
  public static final int WHILE = 33;
  public static final int THEN = 28;
  public static final int END = 29;
  public static final int STRING = 31;
  public static final int LOCAL = 30;
  public static final int MAJ_EQ = 6;
  public static final int PRINT = 38;
  public static final int DO = 24;
  public static final int NOTEQ = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MIN",
  "UMIN",
  "MAJ",
  "MIN_EQ",
  "MAJ_EQ",
  "AND",
  "OR",
  "NOT",
  "SO",
  "SC",
  "EQ",
  "NOTEQ",
  "RO",
  "RC",
  "BO",
  "BC",
  "PLUS",
  "MINUS",
  "STAR",
  "DIV",
  "HAT",
  "CM",
  "DO",
  "FOR",
  "IF",
  "ELSE",
  "THEN",
  "END",
  "LOCAL",
  "STRING",
  "NIL",
  "WHILE",
  "REPEAT",
  "UNTIL",
  "FUNCTION",
  "RETURN",
  "PRINT",
  "ID",
  "NUMBER"
  };
}

